/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniAdvert */

#ifndef _Included_com_qpidnetwork_request_RequestJniAdvert
#define _Included_com_qpidnetwork_request_RequestJniAdvert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniAdvert
 * Method:    MainAdvert
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILcom/qpidnetwork/request/OnAdMainAdvertCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAdvert_MainAdvert
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAdvert
 * Method:    WomanListAdvert
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILcom/qpidnetwork/request/OnAdWomanListAdvertCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAdvert_WomanListAdvert
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniAdvert
 * Method:    PushAdvert
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnAdPushAdvertCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniAdvert_PushAdvert
  (JNIEnv *, jclass, jstring, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
