/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniEMF */

#ifndef _Included_com_qpidnetwork_request_RequestJniEMF
#define _Included_com_qpidnetwork_request_RequestJniEMF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    InboxList
 * Signature: (IIILjava/lang/String;Lcom/qpidnetwork/request/OnEMFInboxListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_InboxList
  (JNIEnv *, jclass, jint, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    InboxMsg
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnEMFInboxMsgCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_InboxMsg
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    OutboxList
 * Signature: (IILjava/lang/String;ILcom/qpidnetwork/request/OnEMFOutboxListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_OutboxList
  (JNIEnv *, jclass, jint, jint, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    OutboxMsg
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnEMFOutboxMsgCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_OutboxMsg
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    MsgTotal
 * Signature: (ILcom/qpidnetwork/request/OnEMFMsgTotalCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_MsgTotal
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    SendMsg
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZILjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ZLcom/qpidnetwork/request/OnEMFSendMsgCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_SendMsg
  (JNIEnv *, jclass, jstring, jstring, jboolean, jint, jstring, jobjectArray, jobjectArray, jboolean, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    UploadImage
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Lcom/qpidnetwork/request/OnEMFUploadImageCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_UploadImage
  (JNIEnv *, jclass, jstring, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    UploadAttach
 * Signature: (ILjava/lang/String;Lcom/qpidnetwork/request/OnEMFUploadAttachCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_UploadAttach
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    DeleteMsg
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/request/OnEMFDeleteMsgCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_DeleteMsg
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    AdmirerList
 * Signature: (IIILjava/lang/String;Lcom/qpidnetwork/request/OnEMFAdmirerListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_AdmirerList
  (JNIEnv *, jclass, jint, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    AdmirerViewer
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnEMFAdmirerViewerCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_AdmirerViewer
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    BlockList
 * Signature: (IILjava/lang/String;Lcom/qpidnetwork/request/OnEMFBlockListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_BlockList
  (JNIEnv *, jclass, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    Block
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/request/OnEMFBlockCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_Block
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    Unblock
 * Signature: ([Ljava/lang/String;Lcom/qpidnetwork/request/OnEMFUnblockCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_Unblock
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    InboxPhotoFee
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnEMFInboxPhotoFeeCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_InboxPhotoFee
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    PrivatePhotoView
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILcom/qpidnetwork/request/OnEMFPrivatePhotoViewCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_PrivatePhotoView
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    GetVideoThumbPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILcom/qpidnetwork/request/OnRequestFileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_GetVideoThumbPhoto
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniEMF
 * Method:    GetVideoUrl
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnGetVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniEMF_GetVideoUrl
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
