/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniProfile */

#ifndef _Included_com_qpidnetwork_request_RequestJniProfile
#define _Included_com_qpidnetwork_request_RequestJniProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniProfile
 * Method:    GetMyProfile
 * Signature: (Lcom/qpidnetwork/request/OnGetMyProfileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniProfile_GetMyProfile
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniProfile
 * Method:    UpdateProfile
 * Signature: (IIIIIIIIIIILjava/lang/String;[Ljava/lang/String;Lcom/qpidnetwork/request/OnUpdateMyProfileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniProfile_UpdateProfile
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jstring, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniProfile
 * Method:    StartEditResume
 * Signature: (Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniProfile_StartEditResume
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniProfile
 * Method:    SaveContact
 * Signature: (Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniProfile_SaveContact
  (JNIEnv *, jclass, jstring, jint, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniProfile
 * Method:    UploadHeaderPhoto
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniProfile_UploadHeaderPhoto
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
