/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniLiveChat */

#ifndef _Included_com_qpidnetwork_request_RequestJniLiveChat
#define _Included_com_qpidnetwork_request_RequestJniLiveChat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    CheckCoupon
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnCheckCouponCallCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_CheckCoupon
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    UseCoupon
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnLCUseCouponCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_UseCoupon
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    QueryChatVirtualGift
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryChatVirtualGiftCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_QueryChatVirtualGift
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    QueryChatRecord
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryChatRecordCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_QueryChatRecord
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    QueryChatRecordMutiple
 * Signature: ([Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryChatRecordMutipleCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_QueryChatRecordMutiple
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    SendPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnLCSendPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_SendPhoto
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    PhotoFee
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnLCPhotoFeeCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_PhotoFee
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    GetPhoto
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Lcom/qpidnetwork/request/OnLCGetPhotoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_GetPhoto
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    UploadVoice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;ILjava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnLCUploadVoiceCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_UploadVoice
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean, jstring, jint, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    PlayVoice
 * Signature: (Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnLCPlayVoiceCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_PlayVoice
  (JNIEnv *, jclass, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    SendGift
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_SendGift
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    QueryRecentVideo
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryRecentVideoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_QueryRecentVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    GetVideoPhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnRequestFileCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_GetVideoPhoto
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLiveChat
 * Method:    GetVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Lcom/qpidnetwork/request/OnGetVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLiveChat_GetVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
