/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniLoveCall */

#ifndef _Included_com_qpidnetwork_request_RequestJniLoveCall
#define _Included_com_qpidnetwork_request_RequestJniLoveCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniLoveCall
 * Method:    QueryLoveCallList
 * Signature: (IIILcom/qpidnetwork/request/OnQueryLoveCallListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLoveCall_QueryLoveCallList
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLoveCall
 * Method:    ConfirmLoveCall
 * Signature: (Ljava/lang/String;ILcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLoveCall_ConfirmLoveCall
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniLoveCall
 * Method:    QueryLoveCallRequestCount
 * Signature: (ILcom/qpidnetwork/request/OnQueryLoveCallRequestCountCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniLoveCall_QueryLoveCallRequestCount
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
