/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniOther */

#ifndef _Included_com_qpidnetwork_request_RequestJniOther
#define _Included_com_qpidnetwork_request_RequestJniOther
#ifdef __cplusplus
extern "C" {
#endif
#undef com_qpidnetwork_request_RequestJniOther_SiteTypeCL
#define com_qpidnetwork_request_RequestJniOther_SiteTypeCL 1L
#undef com_qpidnetwork_request_RequestJniOther_SiteTypeIDA
#define com_qpidnetwork_request_RequestJniOther_SiteTypeIDA 2L
#undef com_qpidnetwork_request_RequestJniOther_SiteTypeCD
#define com_qpidnetwork_request_RequestJniOther_SiteTypeCD 4L
#undef com_qpidnetwork_request_RequestJniOther_SiteTypeLA
#define com_qpidnetwork_request_RequestJniOther_SiteTypeLA 8L
#undef com_qpidnetwork_request_RequestJniOther_SiteTypeAll
#define com_qpidnetwork_request_RequestJniOther_SiteTypeAll 0L
#undef com_qpidnetwork_request_RequestJniOther_SiteTypeUnknow
#define com_qpidnetwork_request_RequestJniOther_SiteTypeUnknow 0L
/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    EmotionConfig
 * Signature: (Lcom/qpidnetwork/request/OnOtherEmotionConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_EmotionConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    GetCount
 * Signature: (ZZZZZZLcom/qpidnetwork/request/OnOtherGetCountCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_GetCount
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    PhoneInfo
 * Signature: (Ljava/lang/String;ILjava/lang/String;IIDIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Lcom/qpidnetwork/request/OnOtherPhoneInfoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_PhoneInfo
  (JNIEnv *, jclass, jstring, jint, jstring, jint, jint, jdouble, jint, jint, jstring, jstring, jstring, jstring, jstring, jint, jint, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    IntegralCheck
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnOtherIntegralCheckCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_IntegralCheck
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    VersionCheck
 * Signature: (ILcom/qpidnetwork/request/OnOtherVersionCheckCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_VersionCheck
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    SynConfig
 * Signature: (Lcom/qpidnetwork/request/OnOtherSynConfigCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_SynConfig
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    OnlineCount
 * Signature: (ILcom/qpidnetwork/request/OnOtherOnlineCountCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_OnlineCount
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    UploadCrashLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_UploadCrashLog
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniOther
 * Method:    InstallLogs
 * Signature: (Ljava/lang/String;IIJJILjava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniOther_InstallLogs
  (JNIEnv *, jclass, jstring, jint, jint, jlong, jlong, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
