/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniMonthlyFee */

#ifndef _Included_com_qpidnetwork_request_RequestJniMonthlyFee
#define _Included_com_qpidnetwork_request_RequestJniMonthlyFee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniMonthlyFee
 * Method:    QueryMemberType
 * Signature: (Lcom/qpidnetwork/request/OnQueryMemberTypeCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMonthlyFee_QueryMemberType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniMonthlyFee
 * Method:    GetMonthlyFeeTips
 * Signature: (Lcom/qpidnetwork/request/OnGetMonthlyFeeTipsCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniMonthlyFee_GetMonthlyFeeTips
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
