/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniQuickMatch */

#ifndef _Included_com_qpidnetwork_request_RequestJniQuickMatch
#define _Included_com_qpidnetwork_request_RequestJniQuickMatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniQuickMatch
 * Method:    QueryQuickMatchLadyList
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnQueryQuickMatchLadyListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniQuickMatch_QueryQuickMatchLadyList
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniQuickMatch
 * Method:    SubmitQuickMatchMarkLadyList
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniQuickMatch_SubmitQuickMatchMarkLadyList
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniQuickMatch
 * Method:    QueryQuickMatchLikeLadyList
 * Signature: (IILcom/qpidnetwork/request/OnQueryQuickMatchLadyLikeListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniQuickMatch_QueryQuickMatchLikeLadyList
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniQuickMatch
 * Method:    RemoveQuickMatchLikeLadyList
 * Signature: ([Ljava/lang/String;Lcom/qpidnetwork/request/OnRequestCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniQuickMatch_RemoveQuickMatchLikeLadyList
  (JNIEnv *, jclass, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
