/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qpidnetwork_request_RequestJniVideoShow */

#ifndef _Included_com_qpidnetwork_request_RequestJniVideoShow
#define _Included_com_qpidnetwork_request_RequestJniVideoShow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    VideoList
 * Signature: (IIIIILcom/qpidnetwork/request/OnVSVideoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_VideoList
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    VideoDetail
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnVSVideoDetailCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_VideoDetail
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    PlayVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/qpidnetwork/request/OnVSPlayVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_PlayVideo
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    WatchedVideoList
 * Signature: (IILcom/qpidnetwork/request/OnVSWatchedVideoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_WatchedVideoList
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    SaveVideo
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnVSSaveVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_SaveVideo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    RemoveVideo
 * Signature: (Ljava/lang/String;Lcom/qpidnetwork/request/OnVSRemoveVideoCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_RemoveVideo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_qpidnetwork_request_RequestJniVideoShow
 * Method:    SavedVideoList
 * Signature: (IILcom/qpidnetwork/request/OnVSSavedVideoListCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_qpidnetwork_request_RequestJniVideoShow_SavedVideoList
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
